spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
